keys:
  - &jmug age1psyctjy329r9v07uqu72vkjl06f26f0epvh6zxejdkwp3m0tnyvq88rnr4 # This key is in cold storage.
  - &hosts:
    - &nixbox age1nhlguc8xf7m4sdn087vqcnc9uj3n4zv09l9043u395acrd3lrscq9fzv66
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *jmug
      - *nixbox
